### ISSUE TITLE
spawn points on opposing checker-board colours may be an advantage?

### ISSUE THREAD

**Issue by john-swu** [sendwithus/battlesnake-server#10]

**Comment by daniel-swu** [comment]
I don't think it's an advantage, because both sides can accommodate for it.

**Comment by exzizt** [comment]
This issue was talked about here quite a bit: https://github.com/battle-snake/battle_snake/issues/5
See my post with the big picture

**Comment by daniel-swu** [comment]
Yeah I've read through that thread, and I'm not seeing how it is an advantage to one side or the other. All snakes have full information and can use it accordingly.

**Comment by exzizt** [comment]
It is a **major** (!) advantage if your snake cannot have head-on collisions with other snakes. It is also unfair to all of the other snakes that can have head-ons collisions, as they can die from them, but yours can't. Does it make more sense now?

**Comment by daniel-swu** [comment]
We have discussed this internally and this is not something that we will be adjusting for in this year's event.

**Comment by slashterix** [comment]
:disappointed: How about next year?
