### ISSUE TITLE
Game crashes often when food / grid size ratio is too high

### ISSUE THREAD

**Issue by robbles** [sendwithus/battlesnake-server#23]
I've been running into a bug where the game will crash and fail to load on really small grids where there's a lot of food. It doesn't happen every time, which leads me to believe it's something to do with food generation overlapping the snake and may very rarely affect larger boards as a result.

To reproduce (on docker image `sendwithus/battlesnake-server:c1d961d529ce`), create a game with the following params:

- width: 5
- height: 5
- max food: 10
- game mode: singleplayer
- one snake URL with name set

It crashes every time for me. Dropping the max food down to 1  fixes the issue and does not seem to ever crash. Max food = 4 seems to inconsistently crash.

**Comment by daniel-swu** [comment]
Yup what's happening here is a buffer is being added around every piece of food, so there just isn't any place left on the board for a snake, 5x5 = 25 squares, 10 pieces of food with a 1 space buffer around them, means no more spaces left. I don't think we actually want to have a buffer around the food when doing snake placement, We'll talk about it internally and figure out how we want to handle it.

**Comment by robbles** [comment]
Ahh, that makes sense! Sounds like there's no risk of this happening on larger board sizes with normal quantities of food then.

**Comment by daniel-swu** [comment]
Going to close this, as we're not going to add any validation around this.
