### ISSUE TITLE
Very slow performance with long (in a sense) snakes in large grids

### ISSUE THREAD

**Issue by aardvarkk** [sendwithus/battlesnake-server#24]
The drawing performance seems to slow to an absolute crawl for our game mode. 

We're using reasonably large grids (say, 30x30), but we set the initial snake lengths to 900 (= 30x30) so that it appears like the tail never moves. This hack enables our game mode to function, but unfortunately it seems to rock the drawing code really hard. Specifically, `drawSnakeBody` seems to be very slow when I profiled it. In Chrome, the display basically stops reacting entirely and, at max, gives a few frames per second.

An optimization that would likely help is to eliminate from drawing any points that lay "on top of" one another. Although our snake starts at 900 units long, visually only 1 square needs to be drawn (since all other coords are on top of each other).

I'm not overly familiar with TypeScript so I'm not super clear on how to implement this myself, but I might try to take a look. If this is an easy fix for somebody I'd appreciate it being patched up and hopefully the game performance will improve significantly!

**Comment by daniel-swu** [comment]
Hey @aardvarkk yes this is a performance problem because it's iterating over every single point in every snake, so as the snakes get longer this gets slower and slower. In the pr I just created, will this solve your problem, in that you don't need to make the snakes really long anymore, because the server will always grow the snake by pinning the tail in place.

**Comment by aardvarkk** [comment]
Hi Daniel,

Yeah -- I noticed the change and it seems to work well! I haven't messed with it much yet, but the drawing seems to be much faster. Thanks very much!

**Comment by daniel-swu** [comment]
No problem, let me know if you run into any other errors. We're also trying to move to an svg renderer instead of canvas based.
