### ISSUE TITLE
Allow the user to go back more turns

### ISSUE THREAD

**Issue by exzizt** [sendwithus/battlesnake-server#27]
Allow the user to go back more turns when running games. Perhaps allow this to be configured, or just hardcode a larger value.

**Comment by daniel-swu** [comment]
Currently the server maintains 20 turns of history, what do you think would be a good value here? There is a tradeoff between memory usage and helpfulness.

**Comment by exzizt** [comment]
It would be best if the user could choose since each person could then tailor the value to their system. But if that's not possible then maybe something like 50?

**Comment by daniel-swu** [comment]
this is now available in the docker image.

**Comment by exzizt** [comment]
Doesn't seem to be working. Here's the command I used:
`docker run -e MAX_HISTORY='100' -it -p 3000:3000 sendwithus/battlesnake-server`

Probably wrong command.

**Comment by exzizt** [comment]
Still can't get this to work. Anybody know the proper way to do this?

**Comment by daniel-swu** [comment]
Yup just looked into it again briefly, and the environment variable is not being respected, at this point though, I don't believe anyone will have time to fix it before the tournament, sorry about that.

**Comment by exzizt** [comment]
No worries!
