### ISSUE TITLE
Multiplayer game mode does not allow single snake to move at all (should probably throw error message)

### ISSUE THREAD

**Issue by poanchen** [sendwithus/battlesnake-server#33]
OS and version: OS X Yosemite
Docker version: 17.03.0-ce-mac1 (15583)
Release or commit: (latest copy, grabbed directly from `docker pull sendwithus/battlesnake-server`)
Steps to reproduce:

1. run `docker run -it -p 3000:3000 sendwithus/battlesnake-server`
2. Head to localhost:3000
3. Create new game
4. put in my snake url and name
5. Hit create game and show button
6. Hit play button (nothing happened)

What I observed:
The game mode is default to Multiplayer. Game with only ONE snake in the Multiplayer mode will NOT be allowed to move at all. However, there were no error message from the docker itself. Without any feedback, it was not easy to know why this is happening. Later on, I played with it a bit and found out that when there are at least one snake in the game. Everything works again. At that point, I realized that the game mode is default to Multiplayer. When I changed to single player with only one snake in the game. Everything works fine now.

Suggestions: (that I think make sense)
There should be some kind of validation on the front end to prevent people from initialing a game with only one snake with game mode Multiplayer. And, when the game mode is switch to single player mode, only one input line should be display instead of 10 of them as of now. (note: this is only my suggestion but I am welcome to hear what others think)

Thank you for reading!
Hope this helps, let me know if you guys have more questions!

Cheers,
Baron

**Comment by daniel-swu** [comment]
Hey @poanchen thanks for the suggestion, we know it's not ideal right now, I think what I'm going to do is remove the dropdown for single player vs multi player, and just infer the value based on the number of snakes that are starting the game. Hopefully will get this available sometime over the weekend.

**Comment by poanchen** [comment]
No problem @daniel-swu. Glad that I could help! I think the solution you proposed is good for now!
At least (when it is fixed), the user would be able to run 1+ snake(s) with the game server. 

(just some personal opinion)
As an user through, I like the freedom of adding one or multiple snakes to the config page without the need to flip that drop-down for single player vs multi player. (I am not sure why we need that drop-down in the first place, for me, it seemed easier tbh without it) However, I did not make the game server so I would not know why it was design this way before haha.

Thanks! Hope it helps!

Cheers,
Baron

**Comment by daniel-swu** [comment]
This should now be fixed in the latest server image.
