### ISSUE TITLE
Visually Missing Snake After Game Restart

### ISSUE THREAD

**Issue by SynthesizedSoul** [sendwithus/battlesnake-server#35]
Seems the game doesn't render all the snakes after a game is restarted.

Steps to reproduce:

1. Add 3 snakes to the game (may work with 2, or more than 3),
2. Start game,
3. Pause game,
4. Restart game.

I was able to reproduce it consistently.

Here's a gif reproduction:

![screen recording 2018-02-23 at 10 40 pm](https://user-images.githubusercontent.com/11812748/36626643-574c7094-18eb-11e8-9ff3-560b32191398.gif)

**Comment by brandon-swu** [comment]
Hey thanks for the bug report! We have this in our backlog already and because it’s not a breaking issue we’re hoping to get to it this week before the event.

Cheers 🍻

**Comment by SynthesizedSoul** [comment]
@brandon-swu Totally low priority, just adding another video in case there's time:

![screen recording 2018-02-23 at 11 10 pm](https://user-images.githubusercontent.com/11812748/36626849-ff681ed8-18ee-11e8-98b3-8111c2aedb81.gif)

**Comment by brandon-swu** [comment]
@SynthesizedSoul we've since pushed out a new docker image that addresses this, let us know if this is still an issue.
