### ISSUE TITLE
Specify not to include / in url

### ISSUE THREAD

**Issue by princessofpillows** [sendwithus/battlesnake-server#41]
The server won't function properly if a url is input ending with a /
Maybe specify not to input a url ending with a /, or do a check for this in the code.

Ex:
http://my_ip:8080/
will become
http://my_ip:8080//start
instead of
http://my_ip:8080/start

**Comment by brandon-swu** [comment]
Thanks @jpatts! We're gonna work on getting a fix out for this in one of the next image pushes.

**Comment by daniel-swu** [comment]
This had been fixed for the move endpoint, but not before calling `/start`. Will deploy a new image by tomorrow.
