### ISSUE TITLE
Game board rapidly shakes back and forth when Chrome's window is maximized

### ISSUE THREAD

**Issue by exzizt** [sendwithus/battlesnake-server#42]
Not sure what is causing it. But it doesn't do it if I un-maximize the window and drag the corners of the window so that it's as "maximized" as possible without actually being maximized.
Latest version of chrome and 3840x2160 resolution.

**Comment by daniel-swu** [comment]
Strange, I've tested this on my monitor with the same resolution and I don't see that happening, are you running the latest server image?

**Comment by exzizt** [comment]
Yup, it's the latest image.

Edit: At 100% zoom or below it happens, but above 100% zoom it doesn't.

**Comment by brandon-swu** [comment]
This is something that won’t be fixed before the tournament (unless it’s fixed as a side effect of fixing something else 😛) as we’re running the tournament on a single machine in an environment we know works clean.
