### ISSUE TITLE
Head-on collision fix

### ISSUE THREAD

**Issue by sjmcgrath** [sendwithus/battlesnake-server#48]
`Collision` doesn't handle the case of a head-on collision where the two Snakes' heads are on adjacent points. I noticed this problem mentioned in #10 with the suggestion that the checker-board start restriction would deal with this, but I think it's more appropriately a head-on collision detection problem.

Essentially, if a snake's first body segment (i.e. head) and second body segment are the same as another snake's second body segment and first body segment, those two snakes have just had a head-on collision even though their heads are not on the same point.

**Comment by brandon-swu** [comment]
I think we'll take a look at getting this merged potentially, thanks for this!

**Comment by daniel-swu** [comment]
Correct, this would be detected as a `BodyCollision` of the 2 snakes and not as a `HeadCollision`

**Comment by john-swu** [comment]
so head-neck in both directions is a head-head. that makes sense as a better solution to the #10

**Comment by sjmcgrath** [comment]
Would love to know if this is going to go in. People I know have feature-toggled their snake for the behaviour, but not fixing it impacts the fairness based on starting positions.

**Comment by brandon-swu** [comment]
@sjmcgrath We've merged in your contribution, I'm going to close this. Cheers!
